image: Visual Studio 2017
build_script:
  - dotnet restore ./WallyMathieu.Collections.sln
  - dotnet build ./WallyMathieu.Collections.sln
test_script:
  - dotnet test ./tests/Tests
branches:
  only: 
    - master
